### ISSUE TITLE
测试问题和建议

### ISSUE THREAD

**Issue by watersoft123** [sinri/SinriScoreDrawer#3]
你好，我对这个js插件很感兴趣，因为我也在将图片赞美诗数字化。当我测试的时候，我发现类似(5 - 5)不能出现连音线，只能显示为普通的 5 - 5，这可能是一个bug，不知道有没有最新的版本。
单个8分或16分音符下划线占用空间似乎看起来比较长，比纸质看起来不那么优美，能不能优化一下。
如果能够播放就更好了，可以参考五线谱的ABCjs，这个我也在使用。

**Comment by sinri** [comment]
可以在 [Playground](https://sinri.github.io/SinriScoreDrawer/playground.html) 尝试下

```
(5 - 5)
(5- 5)
```

对比一下效果。

**Comment by sinri** [comment]
根据文档说明，与数字分离的`-`将被作为无法识别的代码而被 **原样输出** 。

**Comment by sinri** [comment]
关于样式的问题，这个确实有优化空间，和纸质印刷相比还是相形见绌。

**Comment by sinri** [comment]
关于播放功能，有实验性地做过 MacOS 上的APP，达到稳定阶段之后会释出。

**Comment by watersoft123** [comment]
> 可以在 [Playground](https://sinri.github.io/SinriScoreDrawer/playground.html) 尝试下
> 
> ```
> (5 - 5)
> (5- 5)
> ```
> 
> 对比一下效果。

**Comment by watersoft123** [comment]
> 可以在 [Playground](https://sinri.github.io/SinriScoreDrawer/playground.html) 尝试下
> 
> ```
> (5 - 5)
> (5- 5)
> ```
> 
> 对比一下效果。

抱歉，是我理解有误，用 (5- 5)是正确的

**Comment by watersoft123** [comment]
> 关于播放功能，有实验性地做过 MacOS 上的APP，达到稳定阶段之后会释出。

很是期待，不知道能不能提前放出一个测试版？或是私下发我一下，我的邮箱 tjwater@hotmail.com  谢谢！

**Comment by sinri** [comment]
> > 关于播放功能，有实验性地做过 MacOS 上的APP，达到稳定阶段之后会释出。
> 
> 很是期待，不知道能不能提前放出一个测试版？或是私下发我一下，我的邮箱 [tjwater@hotmail.com](mailto:tjwater@hotmail.com) 谢谢！

[MidiBird.app.zip](https://github.com/sinri/SinriScoreDrawer/files/6667960/MidiBird.app.zip)

Just a preview version.
